package gestion;
// Generated 10-ene-2020 12:41:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int idCliente;
     private String dni;
     private String nombre;
     private String apellidos;
     private String direccion;
     private String telefono;
     private Set reservases = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int idCliente, String dni, String nombre) {
        this.idCliente = idCliente;
        this.dni = dni;
        this.nombre = nombre;
    }
    public Clientes(int idCliente, String dni, String nombre, String apellidos, String direccion, String telefono, Set reservases) {
       this.idCliente = idCliente;
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono = telefono;
       this.reservases = reservases;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


