package gestion;
// Generated 10-ene-2020 12:41:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {


     private int idCoche;
     private String matricula;
     private Float precio;
     private String color;
     private String marca;
     private Date fechaMatriculacion;
     private Set reservases = new HashSet(0);

    public Coches() {
    }

	
    public Coches(int idCoche, String matricula, Date fechaMatriculacion) {
        this.idCoche = idCoche;
        this.matricula = matricula;
        this.fechaMatriculacion = fechaMatriculacion;
    }
    public Coches(int idCoche, String matricula, Float precio, String color, String marca, Date fechaMatriculacion, Set reservases) {
       this.idCoche = idCoche;
       this.matricula = matricula;
       this.precio = precio;
       this.color = color;
       this.marca = marca;
       this.fechaMatriculacion = fechaMatriculacion;
       this.reservases = reservases;
    }
   
    public int getIdCoche() {
        return this.idCoche;
    }
    
    public void setIdCoche(int idCoche) {
        this.idCoche = idCoche;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Date getFechaMatriculacion() {
        return this.fechaMatriculacion;
    }
    
    public void setFechaMatriculacion(Date fechaMatriculacion) {
        this.fechaMatriculacion = fechaMatriculacion;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


